export const GET_PROPERTIES_BEGIN = 'GET_PROPERTIES_BEGIN'
export const GET_PROPERTIES_SUCCESS = 'GET_PROPERTIES_SUCCESS'
export const GET_PROPERTIES_FAIL = 'GET_PROPERTIES_FAIL'

export const GET_ALL_HOTELS_BEGIN = 'GET_ALL_HOTELS_BEGIN'
export const GET_ALL_HOTELS_SUCCESS = 'GET_ALL_HOTELS_SUCCESS'
export const GET_ALL_HOTELS_FAIL = 'GET_ALL_HOTELS_FAIL'

export const UPDATE_SELECTED_HOTEL = 'UPDATE_SELECTED_HOTEL'
export const UPDATE_CHECK_IN = 'UPDATE_CHECK_IN'
export const UPDATE_CHECK_OUT = 'UPDATE_CHECK_OUT'


export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'

export const SET_GRIDVIEW = 'SET_GRIDVIEW'
export const SET_LISTVIEW = 'SET_LISTVIEW'

export const UPDATE_SORT = 'UPDATE_SORT'

export const SORT_PRODUCTS = 'SORT_PRODUCTS'

export const UPDATE_FILTERS = 'UPDATE_FILTERS'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'


export const ADD_TO_CART = 'ADD_TO_CART'