export const GET_LOCATIONS_BEGIN = 'GET_LOCATIONS_BEGIN'
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_SUCCESS'
export const GET_LOCATIONS_FAIL = 'GET_LOCATIONS_FAIL'

export const GET_ALL_HOTELS_BEGIN = 'GET_ALL_HOTELS_BEGIN'
export const GET_ALL_HOTELS_SUCCESS = 'GET_ALL_HOTELS_SUCCESS'
export const GET_ALL_HOTELS_FAIL = 'GET_ALL_HOTELS_FAIL'

export const GET_FEATURED_HOTELS_BEGIN = 'GET_FEATURED_HOTELS_BEGIN'
export const GET_FEATURED_HOTELS_SUCCESS = 'GET_FEATURED_HOTELS_SUCCESS'
export const GET_FEATURED_HOTELS_FAIL = 'GET_FEATURED_HOTELS_FAIL'

export const UPDATE_SELECTED_RATING = 'UPDATE_SELECTED_RATING'

export const UPDATE_SELECTED_LOCATION = 'UPDATE_SELECTED_LOCATION'
export const UPDATE_CHECK_IN = 'UPDATE_CHECK_IN'
export const UPDATE_CHECK_OUT = 'UPDATE_CHECK_OUT'


export const LOAD_ALL_HOTELS = 'LOAD_ALL_HOTELS'
export const UPDATE_FILTERS = 'UPDATE_FILTERS'
export const FILTER_HOTELS = 'FILTER_HOTELS'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'


